# I. NumPy.

**Оцінювання даної роботи буде ураховувати якість Вашого коду та текстових відповідей. При наявності ЛИШЕ коду , робота оцінюватися НЕ БУДЕ.**  

**Оформлення текстових відповідей повинно проводитися в текстових комірках ноутбука з використанням синтаксису [LaTeX](https://en.wikibooks.org/wiki/LaTeX/Basics) для оформлення тексту та формул.**

**Роботи ідентифіковані як ІДЕНТИЧНІ одразу отримують 0 балів.**

**При реалізації завдань потрібно використовувати методи з бібліотеки numpy та pandas.**

**Рішення з циклами будуть оцінені в 0 балів.**

0. Імпортувати numpy загальноприйнятим способом.

In [5]:
import numpy as np

1. Визначити список з оцінками студента(ки) за семестр. Використовуючи його, створити одновимірний масив numpy.

In [55]:
marks = [51, 74, 71, 62, 55, 98, 100, 73, 50]
marks_array = np.array(marks)

print(marks_array)

[ 51  74  71  62  55  98 100  73  50]


2. Визначити список зі списками, де кожен рядок списку формально означає магазин, а кожна колонка - певний продукт (батон, яйця першої категорії, молоко та ковбаса), а елементами на пересічі є ціни на ці продукти відповідно. Використовуючи цей список, створити матрицю (двовимірний масив) numpy.

In [90]:
prices = [
    [21.99, 42, 499.99, 63], #формально перший магаз
    [10, 70, 44.50, 90],     #формально другий магаз
    [99.99, 32, 69, 199.99]  ##формально третій магаз
]
prices_array = np.array(prices)

Тип даних: float64


3. Отримайте тип даних значень з масивів завдань 2 та 3. Виведіть їх на екран.

In [57]:
print("Тип даних:", prices_array.dtype)

Тип даних: float64


4. Отримайте форми (кортеж з кількістю рядків та колонок) масивів завдань 2 та 3. Виведіть їх на екран.

In [58]:
print("Форма масиву:", prices_array.shape)

Форма масиву: (3, 4)


5. Створіть одновимірний масив за допомогою спеціальної функції numpy, який би відображав динаміку стабільно зростаючого (з рівними проміжками) прибутку з продажів  за тиждень, де у перший день не було продажів, а в останній день тижня вдалося заробити 1000 грн 50 коп.

In [64]:
profit_array = np.linspace(0, 1000.5, 7)
print("Прибуток:", profit_array)

Прибуток: [   0.    166.75  333.5   500.25  667.    833.75 1000.5 ]


6. Створіть два масиви. Використовуючи їх, продемонструйте відмінність вертикального та горизонтального обʼєднання масивів.

In [65]:
first_array = np.array([[1, 2], [3, 4]])
first_array  = np.array([[5, 6], [7, 8]])

vertical_stack = np.vstack((first_array, first_array ))
horizontal_stack = np.hstack((first_array , first_array ))

print("Вертикальне об'єднання:\n", vertical_stack)
print("Горизонтальне об'єднання:\n", horizontal_stack)

Вертикальне об'єднання:
 [[5 6]
 [7 8]
 [5 6]
 [7 8]]
Горизонтальне об'єднання:
 [[5 6 5 6]
 [7 8 7 8]]


7. Визначити функцію, яка приймає на вході масив і транспонує його. Скористайтесь методом reshape. І не забудьте почати з docstrings.

In [62]:
def transpose_array(arr):
    
    "Транспонує вхідний масив за допомогою методу reshape."
    
    return arr.reshape(arr.shape[1], arr.shape[0])

transpose_prices = transpose_array(prices_array)
print("Транспонована матриця:\n", transpose_prices)

Транспонована матриця:
 [[ 21.99  42.   499.99]
 [ 63.    10.    70.  ]
 [ 44.5   90.    99.99]
 [ 32.    69.   199.99]]


8. Створіть два масиви. Використовучи ці масиви, продемонструйте 1) операцію по-елементного додавання, 2) операцію по-елементного віднімання, 3) множення масиву на число, 4) операцію по-елементного множення, і 5) матричного множення.

In [14]:
x = np.array([2, 4, 6])
y = np.array([1, 3, 5])

print("Поелементне додавання:", x + y)
print("Поелементне віднімання:", x - y)
print("Множення на число:", x * 2)
print("Поелементне множення:", x * y)
print("Матричне множення:", np.dot(x, y)) #обчислюєм скалярний добуток векторів

Поелементне додавання: [ 3  7 11]
Поелементне віднімання: [1 1 1]
Множення на число: [ 4  8 12]
Поелементне множення: [ 2 12 30]
Матричне множення: 44


9. Створіть двовимірний масив (матрицю) та розрахуйте: 1) мінімальне число, 2) максимальне число, 3) суму чисел, 4) мінімальні числа для кожного рядка, 5) максимальні числа для кожного стовпчика.

In [67]:
matrix = np.array([[60, 10, 44], [16, 23, 61], [3, 17, 37]])

print("Мінімальне число:", matrix.min())
print("Максимальне число:", matrix.max())
print("Сума всіх чисел:", matrix.sum())
print("Мінімальні числа в рядках:", matrix.min(axis=1))
print("Максимальні числа в стовпцях:", matrix.max(axis=0))

Мінімальне число: 3
Максимальне число: 61
Сума всіх чисел: 271
Мінімальні числа в рядках: [10 16  3]
Максимальні числа в стовпцях: [60 23 61]


10. Створіть матрицю , де деякі елементи повторюються. Знайдіть унікальні значення елементів цієї матриці та їхні частоти.

In [71]:
matrix_with_duplicates = np.array([[4, 3, 7], [7, 4, 5], [8, 3, 3]])
unique_values, counts = np.unique(matrix_with_duplicates, return_counts=True)

print("Унікальні значення:", unique_values)
print("Частоти значень:", counts)

Унікальні значення: [3 4 5 7 8]
Частоти значень: [3 2 1 2 1]


# II. Importing. Creating DF

0. Імпортувати бібліотеку pandas

In [19]:
import pandas as pd

11. Створити тестовий датафрейм зі списку, що містить записи пацієнтів про їхні прізвища, імена, дату народження, масу тіла та наявність медичного страхування. Одне зі значень зробить пустим. Ознайомтесь з типом кожної колонки.

In [72]:
patients = pd.DataFrame({
    'Прізвище': ['Лазор', 'Фуц', 'Косік'],
    'Імя': ['Роман', 'Ісус', 'Вітя'],
    'Дата народження': ['1990-05-14', '1985-09-23', '1993-07-11'],
    'Маса тіла (кг)': [72, 63.7, None],   # одне значення робим пустим
    'Медстрахування': [False, False, True]
})
print(patients.dtypes)

Прізвище            object
Імя                 object
Дата народження     object
Маса тіла (кг)     float64
Медстрахування        bool
dtype: object


# III. Reading from file

12. Завантажити файл missile_attacks_daily.csv з [Kaggle](https://www.kaggle.com/datasets/piterfm/massive-missile-attacks-on-ukraine?select=missile_attacks_daily.csv). Ознайомитись з описом датасету. Додати файл до папки поточної сесії colab notebook на панелі ліворуч або на гугл диск (локально до проєкту, якщо працюєте у пайчармі). Зчитати датафрейм з файлу та вивести датафрейм на екран. Зверніть увагу на те, щоб всі колонки відповідали наведеним у описі типам даних.

In [ ]:
df = pd.read_csv('D:/Vlad/Все ДЗ(2)/2/AI/Rep-AI/missile_attacks_daily.csv')
print(df.head())

         time_start          time_end           model  \
0  2025-02-02 19:00  2025-02-03 09:00  Shahed-136/131   
1  2025-02-01 21:00  2025-02-02 09:00  Shahed-136/131   
2        2025-02-02        2025-02-02          Молнія   
3        2025-02-02        2025-02-02            ZALA   
4        2025-02-02        2025-02-02        Supercam   

                                        launch_place   target carrier  \
0  Primorsko-Akhtarsk and Chauda, Crimea and Kurs...  Ukraine     NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Oryol ...  Ukraine     NaN   
2                                                NaN    south     NaN   
3                                                NaN    south     NaN   
4                                                NaN    south     NaN   

   launched  destroyed  not_reach_goal  cross_border_belarus  back_russia  \
0      71.0       38.0            25.0                   NaN          NaN   
1      55.0       40.0            13.0                   NaN    

In [88]:
#отримаєм колонки

print(df.columns)

Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'carrier',
       'launched', 'destroyed', 'not_reach_goal', 'cross_border_belarus',
       'back_russia', 'still_attacking', 'affected region',
       'destroyed_details', 'launched_details', 'launch_place_details',
       'source'],
      dtype='object')


# IV. Data understanding

13. Виведіть на екран перші 10 рядків зчитаного датафрейму.

In [52]:
file_path = "missile_attacks_daily.csv"
df = pd.read_csv(file_path)

In [74]:
print("Перші 10 рядків:")
print(df.head(10))

Перші 10 рядків:
         time_start          time_end           model  \
0  2025-02-02 19:00  2025-02-03 09:00  Shahed-136/131   
1  2025-02-01 21:00  2025-02-02 09:00  Shahed-136/131   
2        2025-02-02        2025-02-02          Молнія   
3        2025-02-02        2025-02-02            ZALA   
4        2025-02-02        2025-02-02        Supercam   
5        2025-02-02        2025-02-02          Lancet   
6  2025-01-31 19:00  2025-02-01 09:00       X-59/X-69   
7  2025-01-31 19:00  2025-02-01 09:00           X-31P   
8  2025-01-31 19:00  2025-02-01 09:00       X-22/X-32   
9  2025-01-31 19:00  2025-02-01 09:00     X-101/X-555   

                                        launch_place   target  carrier  \
0  Primorsko-Akhtarsk and Chauda, Crimea and Kurs...  Ukraine      NaN   
1  Primorsko-Akhtarsk and Kursk oblast and Oryol ...  Ukraine      NaN   
2                                                NaN    south      NaN   
3                                                NaN    sou

14. Отримайте інформацію про форму датафрейму.

In [77]:
print("\nФорма датафрейму по кількісті рядків і колонок:", df.shape)


Форма датафрейму по кількісті рядків і колонок: (2079, 17)


15. Отримайте дані про кожну колонку з її назвою, типом даних та кількістю непустих значень.

In [30]:
print("\nІнформація про колонки:")
print(df.info()) #для відображення загальної інфи і тип колонок


Інформація про колонки:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2079 entries, 0 to 2078
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   time_start            2079 non-null   object 
 1   time_end              2079 non-null   object 
 2   model                 2079 non-null   object 
 3   launch_place          1050 non-null   object 
 4   target                2051 non-null   object 
 5   carrier               227 non-null    object 
 6   launched              2076 non-null   float64
 7   destroyed             2075 non-null   float64
 8   not_reach_goal        172 non-null    float64
 9   cross_border_belarus  33 non-null     float64
 10  back_russia           35 non-null     float64
 11  still_attacking       31 non-null     float64
 12  affected region       8 non-null      object 
 13  destroyed_details     309 non-null    object 
 14  launched_details      4 non-null      object 
 

16. Отримайте статистику для колонок числового типу.

In [78]:
print("\nСтатистика колонок числового типу:")
print(df.describe())


Статистика колонок числового типу:
          launched    destroyed  not_reach_goal  cross_border_belarus  \
count  2076.000000  2075.000000      172.000000             33.000000   
mean     11.114644     7.769639       21.720930              2.303030   
std      22.047798    14.678258       19.729546              2.023068   
min       1.000000     0.000000        1.000000              1.000000   
25%       1.000000     1.000000        4.750000              1.000000   
50%       2.000000     1.000000       17.500000              2.000000   
75%       9.000000     7.000000       31.000000              2.000000   
max     193.000000    99.000000      105.000000             10.000000   

       back_russia  still_attacking  
count    35.000000        31.000000  
mean      2.000000         2.709677  
std       1.137593         2.818907  
min       1.000000         1.000000  
25%       1.000000         1.000000  
50%       2.000000         1.000000  
75%       3.000000         3.500000  
ma

17. Отримати кількість унікальних значень у кожній колонці. Вивести на екран значення та кількість цих значень у колонці, яка має найменше унікальних значень.

In [82]:
unique_counts = df.nunique()
min_unique_col = unique_counts.idxmin()

print("\nКількість унікальних значень по колонка:")
print(unique_counts)
print(f"\nКолонка з найменшою кількістю унікальних значень: '{min_unique_col}' {unique_counts[min_unique_col]}")


Кількість унікальних значень по колонка:
time_start               885
time_end                1038
model                     61
launch_place             141
target                    99
carrier                   58
launched                 120
destroyed                 83
not_reach_goal            58
cross_border_belarus       7
back_russia                5
still_attacking            8
affected region            8
destroyed_details        305
launched_details           4
launch_place_details       4
source                   980
dtype: int64

Колонка з найменшою кількістю унікальних значень: 'launched_details' 4


18. На основі отриманої інформації про датасет вище, опишіть по пунктах, що б ви виправили або на що б звернули увагу на кроці очищення даних і чому?

In [89]:
#можна проаналізувати пропущені значення і дублікати
issues = []

missing_values = df.isnull().sum()
if missing_values.any():
    issues.append("Є пропущені значення, необхідно їх заповнити або видалити.")

if df.duplicated().sum() > 0:
    issues.append("Є дублікати, їх слід видалити.")

print("\nВивід:")
for issue in issues:
    print(issue)


Вивід:
Є пропущені значення, необхідно їх заповнити або видалити.


**місце для текстової відповіді**

1.   Пункт списку
2.   Пункт списку

...


# V. Data Cleaning

19. Перетворити колонку launched у цілочислену (Int64). Перевірити, чи все пройшло, як очікувалось.

In [ ]:
df["launched"] = pd.to_datetime(df["launched"], errors="coerce")
df["launched"] = df["launched"].dt.strftime("%Y%m%d").astype("Int64")

#перевірка
print(df["launched"].dtype)
print(df["launched"].head())

Int64
0    19700101
1    19700101
2    19700101
3    19700101
4    19700101
Name: launched, dtype: Int64


20. Видалити колонки, де кількість непустих значень становить менше 30% від загальної кількості записів.

In [40]:
threshold = 0.3 * len(df)
df = df.dropna(thresh=threshold, axis=1)

print("Залишилися колонки:", df.columns)


Залишилися колонки: Index(['time_start', 'time_end', 'model', 'launch_place', 'target', 'launched',
       'destroyed', 'source'],
      dtype='object')


21. Очистити датафрейм від дублікатів (дублюючихся рядків) та записів, де атака продовжувалась відʼємну або нульову кількість часу (що фізично неможливо). Не забудьте оновити індекс. Скільки рядків було видалено? Як ви це перевірили у коді?

In [44]:
initial_rows = df.shape[0]

df = df.drop_duplicates()

df = df[~((df["time_start"] == df["time_end"]) | (df["launch_place"] == 0))]

df = df.reset_index(drop=True)

removed_rows = initial_rows - df.shape[0]
print(f"Видалено {removed_rows} рядків.")

Було видалено 841 рядків.


**місце для текстової відповіді**

In [ ]:
#можна перевірити чи дійсно було видалено дублікати через:

# print(df.duplicated().sum())

22. Виведіть на екран всі рядки, де є хоч одне пропущене значення.

In [50]:
missing_rows = df[df.isnull().any(axis=1)]
print(missing_rows)

            time_start          time_end           model     launch_place  \
2     2025-01-31 19:00  2025-02-01 09:00       X-59/X-69  Voronezh oblast   
3     2025-01-31 19:00  2025-02-01 09:00           X-31P        Black Sea   
4     2025-01-31 19:00  2025-02-01 09:00       X-22/X-32              NaN   
5     2025-01-31 19:00  2025-02-01 09:00     X-101/X-555              NaN   
53    2025-01-03 12:00  2025-01-03 20:00       X-59/X-69              NaN   
...                ...               ...             ...              ...   
1233  2022-10-06 09:00  2022-10-06 11:30       Mohajer-6              NaN   
1234        2022-10-06  2022-10-06 02:00  Shahed-136/131              NaN   
1235        2022-10-05  2022-10-05 02:00  Shahed-136/131              NaN   
1236  2022-10-02 00:00  2022-10-02 02:00  Shahed-136/131              NaN   
1237  2022-09-29 23:00  2022-09-29 23:59  Shahed-136/131              NaN   

                                target  launched  destroyed  \
2           